### ISSUE TITLE
update the documentation

### ISSUE THREAD

**Issue by zsolt-dev** [garygreen/polyfill-io-loader#7]
Hi,

thank you for this library, I would really like to use it, rut I dont know how.

Your documentation states, that I should install it as a **devDependendcy**, so obviously I cannot import it in index.js.

Can you please update your documentation on how to use it?

Where should I put the import? in the webpack config?

So where should I put this:
```
import loadPolyfills from 'polyfill-io-loader!?Promise,NodeList.prototype.forEach,Object.assign';
```

And where should I put this:
```
loadPolyfills(function() {
    // All polyfills have been loaded.
    // Initialise your app here.
});
```

Thank you

**Comment by garygreen** [comment]
Sorry for not getting to this sooner. That documentation could do with tweaking. Personally for my projects I've always added anything that is a "build tool" e.g. webpack, loaders, plugins, etc as a devDependency - but some just like to put it in regular dependencies. It's subjective, so maybe it's not necessary to dictate where to put it when installing, as long as it's installed then should be good to go.

**Comment by zsolt-dev** [comment]
Thank you.

I confirm, it works as devDependendcy. I did `rm -rf node modules` and installed only production deps and it worked.

Created a PR with an example for react.
